### ISSUE TITLE
M2 Architecture Documentation Checklist

### ISSUE THREAD

**Issue by sunnyfisch** [dreamscore-oss/platform#43]
### Task Summary

M2 Architecture Documentation Checklist

### Detailed Description

The technical documentation I describes the results, the requirement analysis and also the planned architecture as well as first design decisions.
ca. 20 pages

### Acceptance Criteria

- [ ] **Source code** as zip
  - [ ] incl. all the configuration files to run the code
   - [ ] generated API documentation as HTML
- [ ] **Use-Case-Model**
  - [ ] All identified use cases are presented in an overview in a UML use case diagram with the corresponding with the associated actors. The UML use case diagram should also represent the differentiation from external systems (system context).
  - [ ] **Fully dressed use cases**: The most important use case(s) must be formulated in detail ("fully dressed") be formulated.
  - [ ] **Casual use cases**: Other important use cases are formulated in a normal ("casual") way, while the rest of the use cases are described briefly.
  - [ ] **Brief use cases**
  - [ ] A **system sequence diagram (SSD)** is created for the standard scenario of the most important and fully formulated use case.
  - [ ] **UI sketches** are created for the most important use cases and, in the case of a more complex UI, the navigation options (dialog flow) are shown in a diagram.
- [ ] **Additional requirements**
  - [ ] Further **functional** and, above all, **non-functional requirements** (**boundary conditions and quality requirements**) are specified here. 
  - [ ] In addition, **important rules** of the problem area (e.g. business or game rules) and **other important information** (e.g. further specifications and constraints for the development of the application) are listed.
- [ ] **Domain model**
  - [ ] A **domain model** is to be developed that represents the (technical) concepts of the most important use cases. The domain model is represented with a (conceptual) UML class diagram.
- [ ] **Software architecture**
  - [ ] Presentation and description of the selected software architecture with justification of the decision.
  - [ ] The software architecture must be presented at least from the perspective of layering (logical architecture) and subsystems/modules using a UML package diagram. 
  - [ ] Special focus is placed on the separation of UI and domain logic as well as the use of frameworks.
  - [ ] If it is a distributed application, the distribution model (client/server, peer-to-peer, etc.) and the selected communication type must be described and justified.
- [ ] **Design artefacts**
  - [ ] Document the existing design with a **design class diagram (DCD)** 
  - [ ] and suitable **interaction diagrams**. Show a corresponding interaction diagram for at least 4 system operations.
  - [ ] Important design decisions made to date must be documented.
- [ ] **Implementation**
  - [ ] Briefly describe here how the selected software architecture was verified. 
  - [ ] The selected software architecture must be verified with a **partial and incomplete implementation (prototype)** of the most important use cases.
  - [ ] A brief explanation of the **test strategy**: Which tests are carried out at which test levels with a justification (unit, integration and system tests).
- [ ] **Projektmanagement**
  - [ ] The planning of previous iterations and the associated effort are recorded and presented. 
  - [ ] For each iteration, the **actual effort** and the **results achieved** are compared with the **planned effort** and the **targets** set and any measures taken are recorded. 
  - [ ] Finally, the **detailed planning of the next iterations**, including an **estimate of the effort involved**, is also included in the submission, as is the **updated risk list**.
- [ ] **Glossary**
  - [ ] A glossary explaining and defining the most important terms in the problem area (see domain model) is to be compiled.
  - [ ] This glossary will be continuously supplemented and updated in the course of the project.

**Comment by boostvolt** [comment]
@sunnyfisch Did you also verify the use cases?
