### ISSUE TITLE
Design artefacts - Interaction Diagram (Sequence- and Communication Diagram)

### ISSUE THREAD

**Issue by sunnyfisch** [dreamscore-oss/platform#58]
### Task Summary

Create 4 interaction diagrams

### Detailed Description

Show a corresponding interaction diagram for at least 4 system operations
Create a sequence diagram for each of the 4 system operations
Create a communication diagram for each of the 4 system operations

### Acceptance Criteria

- [ ] 4 sequence diagrams are created and reviewed
- [ ] 4 Communication diagrams are created and reviewed
- [ ] Diagrams are documented and referenced correctly in the M2 document
